# Prometheus Configuration for IoT Sensor Data Processor

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # IoT Sensor API monitoring
  - job_name: 'iot-sensor-api'
    static_configs:
      - targets: ['iot-sensor-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # MQTT Broker monitoring (if metrics are available)
  - job_name: 'mqtt-broker'
    static_configs:
      - targets: ['mqtt-broker:1883']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Cosmos DB Emulator monitoring (if metrics are available)
  - job_name: 'cosmos-emulator'
    static_configs:
      - targets: ['cosmos-emulator:8081']
    scrape_interval: 60s
    scrape_timeout: 15s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-cache:6379']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker container metrics (if cAdvisor is added)
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
